import type { NextPage } from 'next'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const MainLandLoad = () => import('../components/MainLand').then(mod => mod.MainLand)
const MainLand = dynamic(MainLandLoad, {ssr: false})

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Pixel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLand />
    </>
  )
}

export default Home
